apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MONGODB_URI: mongodb+srv://hawkingradiation42:shrey1234@cluster0.wffbvbx.mongodb.net/?retryWrites=true&w=majority
  JWT_SECRET: PB9pXxlCqLYAEorHtKdIb4ox9lZSfIdTR6noOd1W_54=
type: Opaque
